### ISSUE TITLE
Need more info about GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by jabir366** [shivamguys/irctc-cypress-automation#13]
It would be better if more specific information is given about the `GOOGLE_APPLICATION_CREDENTIALS`. The doubt that I have is. 
- When I try to generate key for a serviceaccount in gcp IAM. saw 2 key formats. json and p12. which one should I use
- A brief step by step instruction to created the application credential would be really great
- When I set the `GOOGLE_APPLICATION_CREDENTIALS` the path to the 2 formats . and run the test  . I got error in app.py
```
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-12-19 23:36:06,961] ERROR in app: Exception on /getCaptchaToText [GET]
Traceback (most recent call last):
  File "/home/jabir/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jabir/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jabir/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jabir/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jabir/JAB/irctc-cypress-automation/irctc-captcha-solve-server/app.py", line 13, in getCaptchaToText
    proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
127.0.0.1 - - [19/Dec/2023 23:36:06] "GET /getCaptchaToText?base64_image=data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAMsAAAAyCAYAAADyZi/iAAAGaUlEQVR42u1db2RdSRSviHhihYp4YsUSVRWxlqiKigqrnngiQlU+1KpH1Iq1aomqFVEl1qqqFdZ+WPsh8mVFRUWpqFpRS0SstSKsiIqqEhERTzzenuFczh5z7537L7l57/fjaOXOnDtz7/xmzjlz5r4LFwAAAAAAAAAAAAAAAAAAAAAAqNfrXSRjJN+TLJK8IdknqZKc8L97JL+T3CfpxlMDkgy4/+E8t90BNZInJAW8eQBkccM6SWfKbblC8g3JAskGyaFY4Y5I/uUVbobkOkYeyHJWbX9P8jPJOEkPSQtfbyMZ4QGs8SqF+xdIpkj+ikFYYx7Opk1aAGTxa7vxUcoeOULKjloG7EiCe08xSZPCrDoPXfoAgCyn2dcfVXcXY+joJlnzGfQmyHCHZFD6RfT/VpJLHIx4wiaZhlmdejEiQZa89LVfdfcgYv1rJB+Uji2SiiFERF03SP5QukwkbxCjssnJwoPD+A7vVFh3MYk5FLENLaq7JxHqDrLT7sG0/0FS84nqTzBJPJh7DGBkNiFZeC9kxcF2f01SzLpNSvWxYx1jQn1UzvlAim3qVabZB+9ZpP3emsmSOFdkYaJsR3B2zYDpzKpNPOgl/nRcjTZFnV2STzOaVHZco3UgS+OR5bVlU3COpI8HYQv7ET/wNYOlDMkyq1Q/dKgzo5z4vgzfRR/fw8M4yNIEZCFVk5Zo0WCIT3BkW25Sas8Q+xkejO/U4RD5knUqIeXHeOPxkP2yY96gNBPEZ7ZnbtExLS5vgizNQZYdpboSg2CJ2sSbksMk82LlqrP/MeBQ/7Go8zagXNES2dIwpJt0IEubirhdBVkamCwc+ZLYjlB3K62B4AMz8/c4+ipy0A6n5Jc9COub2g+aA1kamyx68282Qt2ZjMhSZZ+l6KjrSxeyM/kkXpCUzAohVoqSX0TQR2dZFHkJsjQ2WV7ETSvhXK4sV5Yam2WdIbrmHGb3AaV7OkTntCNZOsI2TkGWxiHLR6X2YoS6F1P2WQY592pPqd0JMsfo2rIoW/Yp80yuKHEmEof3cgKyNDZZqnF1WnbZ02rTJxaT6W+/NBVFrqJPmXVRpuTYjhLIArJInSdJdGa897Oh1E+FET5A17HQ0xZhtQszwwoy/QVkwcpyqiuL0K9T9VfDnovLpBD3mTsEF1ZBlsYmy34efBaXmd0vP0wRvuWUV5ZHoshjkAXRsNSjYTH7fOIQpOhyMOlcfZabIZuS7Wp/54u0TF1l3oEsOSHLmeyzOOrvUOoPHQjvFw2bjxENWw4hi9S5EqBHpwa152EiAlmi6xxOsIO/nTFZ7ricxae/PxVlHvmUuRZxn+XboL6p9BqTX3YpQJc+rVl26PtTkCVnZGG9OjfsnkOdSlaJlMIM+Uepv+9TdkyGmF1XioAd/CWfTVKz0n2ljgEYE+tmSF9+UXp+CinfbUtUBQPyQRZb1vFQQPkh5TCHOcErUQ5gcbLjquUYb4dP+VbVniGfcl2WiSEI34Vcfx/0nMR9S9r38js+wIRcy3IiAlmS6/Y9zyLK9PPfaiLR0YUs8kMPs5xPVZSRKx7IZd5pt6X/l0PaL/2HNyGz9luH3LSvbc9cTCZzESOHOunUBAbueh/L4MhiRZB5AWRJkSxxETDrbkVQs2M5KVnLoN1mxbjt8Gwuq3oTIeUnxHmWGhPEdp7FrAIHJkmSzanbUT94wXpuROjzBmcxgCx5JIsgzLLjGfwuS5uOU2x3jT+Q0Rvh+cwrs603Z+9vVH1Iw4aX3ooFsuSYLGoWXOAz7DWWdzx4S6Jcu7bhA3yQcd7AW2Sb/EDsP1TZtFnn+07G+TA4mzK7avXrztk77OZI2obwsw54lRs5LbMbOP0XX1bvcykHbbqqnH1D8it4W8BZD8x5RZaZHJk7dbUPMplQZwv/FMZyHJ8FaG6iXNZpHH7pHmfUvhFLVM2YPqMR9bRylGoryadkgcYjwHMXp5i/6bWrBuJaDvvzuU+Ez/uS/y3++Yk2Ucc7hHaX/atjS3TuHkYLyOJhmUOkveInIQo8Wz/Taf28wvTntE8F3tupphAbeV7HB8EBW/QlQoj31jnoW5GjcXsR+2cmgt/yZGIC55Msm37fysp5P69zxvQSh5ePeOWpchj3FQcvxlzPvgDNR5YeThT8lfO59tlGlwNplTNih/DEAAAAAAAAAAAAAAAAgFD8B9fBbwuncoOeAAAAAElFTkSuQmCC HTTP/1.1" 500 -
```

**Comment by jabir366** [comment]
I had to change `python` to `python3` in the subprocess call . now the app.py is not crashing . but it repeatedly leading to invalid captcha error. any clue on this?

**Comment by rsksh** [comment]
> It would be better if more specific information is given about the `GOOGLE_APPLICATION_CREDENTIALS`. 

Hi @shivamguys 
It will be better to provide more detailed complete set-up steps for the first time user.

**Comment by shivamguys** [comment]
I was thinking of eliminating this `GOOGLE_APPLICATION_CREDENTIALS` , many of you are not able to understand this bunch or setting up i know they haven't provided easy UI to get things out

**Comment by jabir366** [comment]
There are some pre-requisite I think we need to add to the readme
* We should have a google cloud account
* We need to create a project in GCP Console 
* For the project we need to enable google vision API
* For Enabling Vision API even in free tier. we need to add billing information with a valid credit card
* Once the billing info is added we need to create API Key with the permissions 
* For those who wish to do the Captcha OCR by using some other API locally they can create a custom function for that

**Comment by Nav0410** [comment]
plzz provide a detailed video to use the code for a beginer

**Comment by shivamguys** [comment]
> plzz provide a detailed video to use the code for a beginner
@Nav0410 
**What about having a website where you can add Tatkal details and just pay for it and get your tickets straight away.???**
Note-> I am thining of this to have it in a website feature....
As many newbies won't know how to run this bunch or set it up not familiar with techniques for setting up smoothly...

**Comment by Nav0410** [comment]
It will be very usefull

**Comment by Nav0410** [comment]
Is there any way to get in touch with
You

**Comment by shivamguys** [comment]
we can have a screen share meeting schedule...
@Nav0410

**Comment by Nav0410** [comment]
I successfully made a booking through code for 2 passengers, even when the available tatkal quota is 8. Thank you soo much for the code bro, it's working well. Kindly tell me the procedure to book for a single passenger. Some error was showing while booking for single passenger.

**Comment by shivamguys** [comment]
Ohhh great you can share the time taken to book the tickets.
Glad to know that thanks,
Is it so as many people are reporting error in single passenger let me have a look in to that and i will fix it

**Comment by Nav0410** [comment]
With in 1 min 10 secs, I made a booking, how I can send u that report bro

**Comment by shivamguys** [comment]
@Nav0410  you can share the screenshot in discussion group i will be glad to have this data....
You can hide all passengers information just show time taken etc... make sure you explain what you did example at what time you opened the script at what time you were prepared to book the tickets etc
Thats fast by the way bro thanks a lot for using this

**Comment by Nav0410** [comment]
![Screenshot 2024-02-04 120651](https://github.com/shivamguys/irctc-cypress-automation/assets/157958923/34e7d8b8-a913-4d15-9e90-deb3d5d69a14)
Today i made tatkal booking for 2 people even when the tatkal quota seats available is only 8 seats for that train
i have modified the passenger details in passenger-data.json and username and password in cypress.env.json file
i started the test run at 10.59.35 ms and the ticket got confirmed with in 1.57sec
Thank you so much bro the code.
plzz fix the code to book for single passenger and more than 2 passengers.

**Comment by shivamguys** [comment]
@Nav0410   Here is the test video i just checked for more than 2 passenger have you pulled the latest code ??

[Test Video](https://cloud.cypress.io/projects/7afdkj/runs/15/test-results/5cd7175a-ee1b-4ee3-8843-36d76fde52f3/video?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)

**Comment by shivamguys** [comment]
@Nav0410  kindly pull the latest code and then send me the exact error you are getting....

**Comment by Nav0410** [comment]
I have taken the latest code , but I didn't try for more than 2 passengers,
when I have tried for single passenger, it was showing an error

**Comment by shivamguys** [comment]
@Nav0410 

this is for single passenger isn't causing any error [single passenger test video](https://cloud.cypress.io/projects/7afdkj/runs/14/test-results/33e7392b-20eb-4651-bc2d-37a492f8cdb4/video?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)

**Comment by Nav0410** [comment]
In the passenger list , should I need to remove second passenger details or
should I need to change the code

**Comment by shivamguys** [comment]
Just remove second passenger details....
No need to touch the code only passengerdetails.json
@Nav0410

**Comment by Nav0410** [comment]
I'm getting this error when I remove the passenger details

**Comment by shivamguys** [comment]
What's the error? @Nav0410

**Comment by Nav0410** [comment]
While filling the passenger details , I got the error

**Comment by Nav0410** [comment]
Can u plzz guide me here , how to go ahead

**Comment by shivamguys** [comment]
But share me the error i can't see anything ???
@Nav0410

**Comment by Nav0410** [comment]
This is the error I'm getting

**Comment by Nav0410** [comment]
Did I made any mistake in removing the passenger name?

**Comment by shivamguys** [comment]
Bro stop replying from email i cannot see any error you are posting @Nav0410

**Comment by Nav0410** [comment]
How to contact you bro
WhatsApp or instagram

**Comment by shivamguys** [comment]
ping me on WA 8604949532 , going to have lunch but will be in touch with you later...
