### ISSUE TITLE
Cypress configuration error

### ISSUE THREAD

**Issue by siddhu2310** [shivamguys/irctc-cypress-automation#19]
I'm installed this in WIndows Machine.
I'm gettign an error

***Error***
```
cypress
irctc-cypress-automation-main
[v13.6.3](https://on.cypress.io/changelog#13-6-3)

Docs

Log in
Cypress configuration error
Try again
Error
Your configFile is invalid: C:\Users\Siddharth\Downloads\irctc-cypress-automation-main\cypress.config.js

It threw an error when required, check the stack trace below:

cypress.config.js:1:26
> 1 | const { defineConfig } = require("cypress");
    |                          ^
  2 | 
  3 | module.exports = defineConfig({
  4 |   defaultCommandTimeout: 120000,
  5 | 
[Stack trace](http://localhost:49783/__launchpad/index.html#)
Error: Cannot find module 'cypress'
Require stack:
- C:\Users\Siddharth\Downloads\irctc-cypress-automation-main\cypress.config.js
- C:\Users\Siddharth\AppData\Local\Cypress\Cache\13.6.3\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js
- C:\Users\Siddharth\AppData\Local\Cypress\Cache\13.6.3\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\require_async_child.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object. (C:\Users\Siddharth\Downloads\irctc-cypress-automation-main\cypress.config.js:1:26)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at loadFile (C:\Users\Siddharth\AppData\Local\Cypress\Cache\13.6.3\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14)
    at EventEmitter. (C:\Users\Siddharth\AppData\Local\Cypress\Cache\13.6.3\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:519:28)
    at process. (C:\Users\Siddharth\AppData\Local\Cypress\Cache\13.6.3\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:519:28)
    ```

**Comment by siddhu2310** [comment]
REsolved.
